version: 2.1

orbs:
  node: circleci/node@4.9.0

workflows:
  build_test:
    jobs:
      - node/run:
          version: '16.10'
          pkg-manager: npm
          npm-run: lint
      - node/test:
          version: '16.10'
          pkg-manager: npm
  deploy:
    filters:
      branches:
        only:
          - master
    jobs:
      build:
        steps:
          - node/run:
              version: '16.10'
              pkg-manager: npm
              npm-run: build:prod
      deploy:
        steps:
          - run:
            name: Deploy via SCP
            command: scp build/bundle.min.js build/bundle.min.js/LICENSE.txt "$DEPLOY_USER@$DEPLOY_SERVER:~/WordPress_01/"
            
