version: 2.1

orbs:
  node: circleci/node@4.9.0

jobs:
  build:
    machine:
      image: ubuntu-2004:202111-01
    steps:
      - checkout
      - run: npm install
      - run: npm run build:prod
      - store_artifacts:
          path: /build/bundle.min.js

  deploy:
    machine:
      image: ubuntu-2004:202111-01
    steps:
      - run:
          name: Deploy via SFTP
          command: ls -Fla && scp /build/bundle.min.js /build/bundle.min.js/LICENSE.txt "$DEPLOY_USER@$DEPLOY_SERVER:~/WordPress_01/"

workflows:
  lint_test:
    jobs:
      - node/run:
          version: '16.10'
          pkg-manager: npm
          npm-run: lint
      - node/test:
          version: '16.10'
          pkg-manager: npm
  build_deploy:
    jobs:
      - build
      - deploy:
        filters:
          branches:
            only:
              - main
