version: 2.1

orbs:
  node: circleci/node@4.9.0

jobs:
  build:
    machine:
      image: ubuntu-2004:202111-01
    steps:
      - checkout
      - run: npm install
      - run: npm run build:prod
      - persist_to_workspace:
          root: build
          paths:
            - bundle.min.js
            - bundle.min.js.LICENSE.txt

  deploy:
    machine:
      image: ubuntu-2004:202111-01
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Deploy via SFTP
          command: ls -Fla /tmp/workspace && scp build/bundle.min.js build/bundle.min.js.LICENSE.txt "$DEPLOY_USER@$DEPLOY_SERVER:~/WordPress_01/"

workflows:
  lint_test:
    jobs:
      - node/run:
          version: '16.10'
          pkg-manager: npm
          npm-run: lint
      - node/test:
          version: '16.10'
          pkg-manager: npm
  build_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
