name: Deploy

on:
  pull_request:
    types:
      - closed
jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    environment:
        name: production
        url: https://throughapinhole.com

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Enable corepack
      run: corepack enable
    - name: Install dependencies
      run: yarn install
    - name: Build for production
      run: yarn build:prod
    - name: Setup SSH
      env:
        PRIV_KEY: ${{ secrets.DEPLOY_PRIV_KEY }}
        PUB_KEY: ${{ secrets.DEPLOY_PUB_KEY }}
        HOSTNAME: ${{ secrets.DEPLOY_HOSTNAME }}
      run: |
        mkdir -p ~/.ssh/
        echo "$PRIV_KEY" > ~/.ssh/id_rsa
        echo "$PUB_KEY" > ~/.ssh/id_rsa.pub
        chmod 600 ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa.pub
        ssh-keyscan -H $HOSTNAME >> ~/.ssh/known_hosts
    - name: copy builds to server
      env:
        DEPLOY_USERNAME: ${{ secrets.DEPLOY_USERNAME }}
        DEPLOY_HOSTNAME: ${{ secrets.DEPLOY_HOSTNAME }}
      run: |
        scp ./build/bundle.min.js ./build/bundle.min.js.LICENSE.txt "$DEPLOY_USERNAME@$DEPLOY_HOSTNAME:/WordPress_01/"